// create user (post)
POST http://localhost:5050/users
Content-Type: application/json

{
  "name": "User69",
  "email": "random69@gmail.com",
  "password": "123456",
  "confPassword": "123456",
  "role": "user"
}

###
// get all users
GET http://localhost:5050/users

###
// get single user or by id
GET http://localhost:5050/users/f61b973a-9669-46af-b86f-7dd78de3f7a5

###
// update user (patch)
PATCH http://localhost:5050/users/86a4f1e8-9280-472a-9d37-a82a2f33a5ac
Content-Type: application/json

{
  "name": "Axelcio",
  "email": "axelcio@gmail.com",
  "password": "",
  "confPassword": "",
  "role": "user"
}

###
// delete user
DELETE http://localhost:5050/users/651081eb-0424-454d-8c0c-93a0b151e66e


///////// AUTHENTICATION /////////
###
// Login User
POST http://localhost:5050/login
Content-Type: application/json

{
  "email": "admin@gmail.com",
  "password": "123456"
}

###
GET http://localhost:5050/me
// Tanpa menggunakan connect-session-sequelize akan otomotis logout apabila server berhenti

###
DELETE http://localhost:5050/logout
